### ISSUE TITLE
`rw` vs. `rewrite`

### ISSUE THREAD

**Issue by vvs-** [IPDSnelting/tba-2021#1]
Hi!

In light of the recent discussion on Zulip. @Kha, don't you think that `rewrite` already does what you propose? `rewrite` doesn't close the goal with `rfl` in contrast to `rw`.

**Comment by Kha** [comment]
Yes, but I believe that is both an accidental as well as terrible naming decision :) . So I didn't even mention it when presenting the issue.

**Comment by vvs-** [comment]
I agree. This is confusing. But not mentioning it is confusing too :)

**Comment by Kha** [comment]
Tactics not mentioned on the slides obviously don't exist :)

**Comment by vvs-** [comment]
That's fair :)
